# Generated by Django 5.1.5 on 2025-01-26 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://collection.cloudinary.com/dz2s8rwti/fb798700708a6ed1d9f9f6772f628fd6', max_length=255, verbose_name='profile_pics'),
            preserve_default=False,
        ),
    ]
